services:
  - type: worker
    name: telegram-interaction-bot
    env: python
    plan: free
    buildCommand: "pip install --upgrade pip && pip install --only-binary=:all: -r requirements.txt"
    startCommand: "python -m bot.main"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: GROUP_IDS
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: TZ
        value: Asia/Ho_Chi_Minh
